In [15]:
import numpy as np
#Solution to first question
arange_array = np.arange(100, 200, 10)
print(arange_array)
B = np.reshape(arange_array, (-1, 2))
print(B)(5*2 matrix)


[100 110 120 130 140 150 160 170 180 190]
[[100 110]
 [120 130]
 [140 150]
 [160 170]
 [180 190]]
[[179 140]
 [163 112]
 [167 103]
 [104 140]
 [109 100]]


2

In [20]:
#Solution to 2nd Question
x = np.random.random((3,3,3))
print(x)
maxval=np.max(x)
minval=np.min(x)
print("Max Value",maxval)
print("Min Value",minval)

[[[0.44864235 0.82810329 0.08651417]
  [0.02790486 0.70539526 0.46577082]
  [0.96626602 0.70749699 0.72859882]]

 [[0.36218817 0.52548836 0.68061541]
  [0.03396791 0.94965418 0.52049785]
  [0.31733859 0.87067987 0.22894943]]

 [[0.22143775 0.92051043 0.99622309]
  [0.20082204 0.88519963 0.17712888]
  [0.08620573 0.63083519 0.98888112]]]
Max Value 0.9962230928392527
Min Value 0.027904863549143788


In [21]:
#Solution to 3rd Question
Z = np.diag([1, 2, 3, 4, 5])
print(Z)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [29]:
# Solution to Extract all odd numbers from arr
a = np.array([1,2,3,4,5,6,6,7,7,8,9])
b= a[a % 2 == 1]
print("All odd numbers in b",b)

[1 3 5 7 7 9]


In [27]:
# Solution to Replace all odd numbers in arr with -1
odd_values = (a%2 == 1) 
a[odd_values] = -1
print(a)

[-1  2 -1  4 -1  6  6 -1 -1  8 -1]


In [30]:
# Solution to Question 5.Write a NumPy program to create a 3x3 identity matrix,
# i.e. diagonal elements are 1,the rest are 0.
D = np.diag([1, 1, 1])
print(D)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [34]:
# Soltion to question 6 Write a NumPy program to convert an array to a float
# type.
arr_fl = np.array([[1,2], [3,4], [5,6]])
print( arr_fl)
print(arr_fl.dtype)


arr_fl = np.array([[1,2], [3,4], [5,6]] , dtype = np.float64)
print(" A Float Array: \n" , arr_fl)
print(arr_fl.dtype)

[[1 2]
 [3 4]
 [5 6]]
int32
 A Float Array: 
 [[1. 2.]
 [3. 4.]
 [5. 6.]]
float64


In [35]:
# Solution to question 7 Write a NumPy program to generate five random
# numbers from the normal distribution.
x = np.random.normal(size=5)
print(x)

[ 1.38684547  0.36190715 -0.6503964  -0.01799294  0.88585466]


In [58]:
# Solution to question 8 Following is the input NumPy array delete column two
# and insert following new column in its place.
sampleArray=np.array([[34,43,73],[82,22,12],[53,94,66]])
print(sampleArray)
sampleArray[0,1]=sampleArray[1,1]=sampleArray[2,1]=10
print("After overwriting 2nd column\n",sampleArray)

[[34 43 73]
 [82 22 12]
 [53 94 66]]
After overwriting 2nd column
 [[34 10 73]
 [82 10 12]
 [53 10 66]]


In [63]:
# Solution of Question 9 Write a NumPy program to compute the multiplication
# of two given matrices.
p = [[1, 4], [3, 1]]
q = [[1], [3]]
print("original matrix:")
print(p)
print(q)
result1 = np.dot(p, q)
result2 = np.multiply(p, q)
print("Result of the said matrix multiplication:")
print(result1)# Dot product Please Ignore
print(result2)# aCtual Result

original matrix:
[[1, 4], [3, 1]]
[[1], [3]]
Result of the said matrix multiplication:
[[13]
 [ 6]]
[[1 4]
 [9 3]]


In [64]:
# Solution to Question 10 Write a NumPy program to create a random vector of
# size 10 and sort it.
x = np.random.random(10)
print("Original array:")
print(x)
x.sort()
print("Sorted array:")
print(x)

Original array:
[0.72854546 0.00251629 0.2395587  0.34955055 0.62280634 0.8636066
 0.42315401 0.88611135 0.40876443 0.73678658]
Sorted array:
[0.00251629 0.2395587  0.34955055 0.40876443 0.42315401 0.62280634
 0.72854546 0.73678658 0.8636066  0.88611135]


In [68]:
# Solution to question 10 Write a NumPy program to compute the covariance
# matrix of two arrays.
Run = np.array([0, 56, 40, 10])
Balls = np.array([6, 27, 28, 6])
print("\nRun Scored:")
print(x)
print("\nBalls Faced:")
print(y)
print("\nCovariance matrix of the said arrays:\n",np.cov(x, y))


Run Scored:
[ 0 56 37]

Balls Faced:
[ 6 27 25]

Covariance matrix of the said arrays:
 [[811.         319.5       ]
 [319.5        134.33333333]]


In [76]:
# Solution of Question 12 12.Create a 4X2 integer array and Prints its
# i)The shape of an array.
# ii) Array dimensions.
# iii) The Length of each element of the array in bytes
a=  np.array([[1, 4], [3, 1], [2,4],[3,3]])
print("Actual Array\n",a)
print("\n Shape : " , a.shape)
print("\n Dimension : " , a.ndim)
print("\n Length of each element of the array : ", a.itemsize)

Actual Array
 [[1 4]
 [3 1]
 [2 4]
 [3 3]]

 Shape :  (4, 2)

 Dimension :  2

 Length of each element of the array :  4


In [79]:
#Solution to question 13 Write a NumPy program to concatenate element-wise
# two arrays of string.
x1 = np.array(['Virat', 'Shreyas'], dtype=np.str)
x2 = np.array([' Kohli', ' Iyer'], dtype=np.str)
print("Array1:")
print(x1)
print("Array2:")
print(x2)
new_array = np.char.add(x1, x2)
print("new array:")
print(new_array)

Array1:
['Virat' 'Shreyas']
Array2:
[' Kohli' ' Iyer']
new array:
['Virat Kohli' 'Shreyas Iyer']


In [89]:
# Solution to Question 14 Write a NumPy program to capitalize the first letter,
# lowercase, uppercase, swapcase, title-case of all the
# elements of a given array.
a=np.array(['i am watching cricket match.'])
print(np.char.capitalize(a))
print("Original Array\n", new_array)
l=np.char.lower(new_array)
print("Lower Case\n",l)
au=np.char.upper(new_array)
print("uper Case\n",u)
s=  np.char.swapcase(new_array)
print("Swap Case\n",s)
t = np.char.title(a)
print("Array before Title case\n",a)
print("Title Case\n",t)

['I am watching cricket match.']
Original Array
 ['Virat Kohli' 'Shreyas Iyer']
Lower Case
 ['virat kohli' 'shreyas iyer']
uper Case
 ['VIRAT KOHLI' 'SHREYAS IYER']
Swap Case
 ['vIRAT kOHLI' 'sHREYAS iYER']
Array before Title case
 ['i am watching cricket match.']
Title Case
 ['I Am Watching Cricket Match.']


In [90]:
# Solution to Question 15 Write a NumPy program to convert a given array into
# a list.
arr = np.array([11, 21, 19])
print(f'NumPy Array: {arr}')
print(type(arr))

list1 = arr.tolist()
print(f'List: {list1}')
print(type(list1))

NumPy Array: [11 21 19]
<class 'numpy.ndarray'>
List: [11, 21, 19]
<class 'list'>


In [94]:
# Solution to Question 16 Write a NumPy program to compute the sum of all
# elements, sum of each column and sum of each row of a
# given array.
x = np.array([[5,1,8],[2,3,4],[7,6,4]])
print("Original array:")
print(x)
print("Sum of all elements:")
print(np.sum(x))
print("Sum of each column:")
print(np.sum(x, axis=0))
print("Sum of each row:")
print(np.sum(x, axis=1))

Original array:
[[5 1 8]
 [2 3 4]
 [7 6 4]]
Sum of all elements:
40
Sum of each column:
[14 10 16]
Sum of each row:
[14  9 17]


In [96]:
# Solution to question 17 Write a NumPy program to create a random 10x4
# array and extract the first five rows of the array and store
# them into a variable.
x = np.random.rand(10, 4)
print("Original array: ")
print(x)
y= x[:5, :]
print("First 5 rows of the above array:")
print(y)

Original array: 
[[0.07252149 0.08738211 0.74006201 0.23003313]
 [0.97105561 0.6992084  0.47103063 0.45139093]
 [0.36966211 0.17525166 0.38026682 0.98249417]
 [0.70289645 0.71746149 0.73055903 0.98379222]
 [0.5140305  0.15233475 0.40069358 0.98674902]
 [0.97690564 0.00829046 0.31005207 0.62216031]
 [0.21488802 0.13705668 0.21614223 0.35895641]
 [0.77722422 0.63592167 0.54168315 0.57721851]
 [0.1718276  0.74573876 0.71244937 0.18233679]
 [0.12536113 0.66204757 0.24543169 0.55086918]]
First 5 rows of the above array:
[[0.07252149 0.08738211 0.74006201 0.23003313]
 [0.97105561 0.6992084  0.47103063 0.45139093]
 [0.36966211 0.17525166 0.38026682 0.98249417]
 [0.70289645 0.71746149 0.73055903 0.98379222]
 [0.5140305  0.15233475 0.40069358 0.98674902]]


In [2]:
# Solution of Question 18 Write a NumPy program to get the unique elements of
# a 1D and 2D array.
import numpy as np
rr = np.array([3, 3, 4, 5, 6, 5, 6, 4]) 
# find unique element  from a 1 D array 
rslt = np.unique(rr)
print(rslt)

[3 4 5 6]


In [4]:
#Unique Element form 2d
arr = np.array([[9, 9, 7, 7], 
              [3, 4, 3, 4]]) 
  
# find unique element from a 2 D array 
rslt = np.unique(arr) 
print(rslt)

[3 4 7 9]


In [6]:
# Solution of Question 19  Write a NumPy program to get the unique elements of
# an array. # As per the question we have three element
arr= np.array([ -10, 12.12,-0.2])
rslt = np.unique(arr) 
print(rslt)

[-10.    -0.2   12.12]


In [7]:
# Solution Question 20 Write a NumPy program to save a given array to a text
# file and load it. You have to save and load files using
# numpy library
import os
x = np.arange(12).reshape(4, 3)
print("Original array:")
print(x)
header = 'col1 col2 col3'
np.savetxt('temp.txt', x, fmt="%d", header=header) 
print("After loading, content of the text file:")
result = np.loadtxt('temp.txt')
print(result)

Original array:
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
After loading, content of the text file:
[[ 0.  1.  2.]
 [ 3.  4.  5.]
 [ 6.  7.  8.]
 [ 9. 10. 11.]]
